### ISSUE TITLE
Error in dplyr::left_join()

### ISSUE THREAD

**Issue by bhagya-ct** [kvittingseerup/IsoformSwitchAnalyzeR#165]
isoformSwitchAnalysisPart2() stops at step 3 with the following error:

Step 1 of 5 : Importing external sequence analysis...
Step 2 of 5 : Analyzing alternative splicing...
Step 3 of 5 : **Predicting functional consequences...**
Error in dplyr::left_join(transcriptData, orfData, by = "isoform_id",  : 
  `...` must be empty.
✖ Problematic argument:
• all.x = TRUE
Error: with piece 1: 
  isoformUpregulated isoformDownregulated comparison
1 FUNEC_00195.mRNA.2   FUNEC_00195.mRNA.1          1

Any suggestion?

Do you think a change in dplyr causing this error?

Best,
Bhagya

**Comment by kvittingseerup** [comment]
Yep. Just upgrade to the newest GitHub version and it should work 😊

**Comment by bhagya-ct** [comment]
Thank you for your quick reply. 

I am afraid that the error still exists with the current version of IsoformSwitchAnalyzeR.
'''
 > packageVersion('IsoformSwitchAnalyzeR')
[1] '2.1.2'

'''

**Comment by kvittingseerup** [comment]
Thanks for reporting it again - had missed a few of the dplyr update problems. I just pushed a fix - can you try 2.1.3?

**Comment by gregvall** [comment]
Hello I was encountering the same issue and it is still occurring after I update to 2.1.3. Thank you in advance for your help

**Comment by kvittingseerup** [comment]
@gregvall Did you restart R after updating the package? That is sometimes necessary (since you update an already loaded R package)?

If that did not work, could you post your code and your error message?

**Comment by gregvall** [comment]
@kvittingseerup 
Apologies, I did nor restart R when reattempting to use the function. It does in fact work. 
Thank you for being so prompt with your response. 

Greg

**Comment by kvittingseerup** [comment]
I also think it is strange the R people have not solve this issue. Thanks for checking!
